/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab6p2_linsyposso;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author 29164
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jD_crearE = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_nombreE = new javax.swing.JTextField();
        tf_paisE = new javax.swing.JTextField();
        tf_ciudad = new javax.swing.JTextField();
        tf_estadio = new javax.swing.JTextField();
        jB_aggE = new javax.swing.JButton();
        jD_crearJ = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_nombreJ = new javax.swing.JTextField();
        jS_edad = new javax.swing.JSpinner();
        CB_pos = new javax.swing.JComboBox<>();
        jB_aggJ = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jD_tranferir = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_jugadores = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jB_ce = new javax.swing.JButton();
        jB_cj = new javax.swing.JButton();
        jB_transfe = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jm_ops = new javax.swing.JMenu();
        jmi_ce = new javax.swing.JMenuItem();
        jmi_cj = new javax.swing.JMenuItem();
        jmi_transfe = new javax.swing.JMenuItem();
        jm_help = new javax.swing.JMenu();

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Crear Equipos");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 260, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Nombre del Equipo");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("Pais del Equipo");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("Ciudad");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 255));
        jLabel7.setText("Estadio");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab6p2_linsyposso/Boroa Pet (1).jpg"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tf_nombreE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_nombreE.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(tf_nombreE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 220, 30));
        jPanel2.add(tf_paisE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 220, 30));
        jPanel2.add(tf_ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 220, 30));
        jPanel2.add(tf_estadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 200, 30));

        jB_aggE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_aggE.setText("Agregar");
        jPanel2.add(jB_aggE, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 110, 40));

        javax.swing.GroupLayout jD_crearELayout = new javax.swing.GroupLayout(jD_crearE.getContentPane());
        jD_crearE.getContentPane().setLayout(jD_crearELayout);
        jD_crearELayout.setHorizontalGroup(
            jD_crearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
        jD_crearELayout.setVerticalGroup(
            jD_crearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setForeground(new java.awt.Color(255, 204, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Crear Jugadores");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 310, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 80, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Edad");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Posicion");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        tf_nombreJ.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_nombreJ.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(tf_nombreJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 260, 30));

        jS_edad.setModel(new javax.swing.SpinnerNumberModel(15, 15, 45, 1));
        jPanel3.add(jS_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, -1));

        CB_pos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portero", "Delantero", "Defensa", "Centro" }));
        jPanel3.add(CB_pos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 100, -1));

        jB_aggJ.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_aggJ.setText("Agregar");
        jB_aggJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_aggJMouseClicked(evt);
            }
        });
        jPanel3.add(jB_aggJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 100, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab6p2_linsyposso/Boroa Pet (1).jpg"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jD_crearJLayout = new javax.swing.GroupLayout(jD_crearJ.getContentPane());
        jD_crearJ.getContentPane().setLayout(jD_crearJLayout);
        jD_crearJLayout.setHorizontalGroup(
            jD_crearJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );
        jD_crearJLayout.setVerticalGroup(
            jD_crearJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Transferencias");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 280, -1));

        jList_jugadores.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jList_jugadores);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 180, 280));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Jugadores");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 80, -1));

        jButton3.setText("Transferir ->");
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, 30));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Equipos");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jTree1);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 142, 200, 290));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Equipos");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 60, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab6p2_linsyposso/Boroa Pet (1).jpg"))); // NOI18N
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jD_tranferirLayout = new javax.swing.GroupLayout(jD_tranferir.getContentPane());
        jD_tranferir.getContentPane().setLayout(jD_tranferirLayout);
        jD_tranferirLayout.setHorizontalGroup(
            jD_tranferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        jD_tranferirLayout.setVerticalGroup(
            jD_tranferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jToolBar1.setBackground(new java.awt.Color(0, 153, 153));
        jToolBar1.setRollover(true);

        jB_ce.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_ce.setText("Crear Equipos");
        jB_ce.setFocusable(false);
        jB_ce.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB_ce.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jB_ce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_ceMouseClicked(evt);
            }
        });
        jToolBar1.add(jB_ce);

        jB_cj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_cj.setText("Crear Jugadores");
        jB_cj.setFocusable(false);
        jB_cj.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB_cj.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jB_cj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_cjMouseClicked(evt);
            }
        });
        jToolBar1.add(jB_cj);

        jB_transfe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jB_transfe.setText("Transferencias");
        jB_transfe.setFocusable(false);
        jB_transfe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB_transfe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jB_transfe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_transfeMouseClicked(evt);
            }
        });
        jToolBar1.add(jB_transfe);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab6p2_linsyposso/Boroa League Fantasy (1) (1) (1).jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido a Boroa League Fantasy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(191, 191, 191))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 108, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 510));

        jm_ops.setText("Opciones");

        jmi_ce.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmi_ce.setText("Crear Equipos");
        jmi_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ceActionPerformed(evt);
            }
        });
        jm_ops.add(jmi_ce);

        jmi_cj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmi_cj.setText("Crear Jugadores");
        jmi_cj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cjActionPerformed(evt);
            }
        });
        jm_ops.add(jmi_cj);

        jmi_transfe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmi_transfe.setText("Transferencias");
        jmi_transfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_transfeActionPerformed(evt);
            }
        });
        jm_ops.add(jmi_transfe);

        jMenuBar2.add(jm_ops);

        jm_help.setText("Ayuda");
        jMenuBar2.add(jm_help);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ceActionPerformed
        abreCrearE();
    }//GEN-LAST:event_jmi_ceActionPerformed

    private void jmi_cjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cjActionPerformed
        abreCrearJ();
    }//GEN-LAST:event_jmi_cjActionPerformed

    private void jB_ceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_ceMouseClicked
        abreCrearE();
    }//GEN-LAST:event_jB_ceMouseClicked

    private void jB_cjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_cjMouseClicked
        abreCrearJ();
    }//GEN-LAST:event_jB_cjMouseClicked

    private void jmi_transfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_transfeActionPerformed
        abreTransfer();
    }//GEN-LAST:event_jmi_transfeActionPerformed

    private void jB_transfeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_transfeMouseClicked
        abreTransfer();
    }//GEN-LAST:event_jB_transfeMouseClicked

    private void jB_aggJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_aggJMouseClicked
        Jugadores nuevoj = new Jugadores(tf_nombreJ.getText(),
                (Integer) jS_edad.getValue(),
                CB_pos.getSelectedItem().toString());
        DefaultListModel modelo = (DefaultListModel) jList_jugadores.getModel();
        modelo.addElement(nuevoj);
        //limpiar campos
        tf_nombreJ.setText("");
        jS_edad.setValue(15);
        CB_pos.setSelectedIndex(0);


    }//GEN-LAST:event_jB_aggJMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private void abreCrearE() {
        jD_crearE.pack();
        jD_crearE.setLocationRelativeTo(this);
        jD_crearE.setModal(true);
        jD_crearE.setVisible(true);
    }

    private void abreCrearJ() {
        jD_crearJ.pack();
        jD_crearJ.setLocationRelativeTo(this);
        jD_crearJ.setModal(true);
        jD_crearJ.setVisible(true);
    }

    private void abreTransfer() {
        jD_tranferir.pack();
        jD_tranferir.setLocationRelativeTo(this);
        jD_tranferir.setModal(true);
        jD_tranferir.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_pos;
    private javax.swing.JButton jB_aggE;
    private javax.swing.JButton jB_aggJ;
    private javax.swing.JButton jB_ce;
    private javax.swing.JButton jB_cj;
    private javax.swing.JButton jB_transfe;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jD_crearE;
    private javax.swing.JDialog jD_crearJ;
    private javax.swing.JDialog jD_tranferir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList_jugadores;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner jS_edad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenu jm_help;
    private javax.swing.JMenu jm_ops;
    private javax.swing.JMenuItem jmi_ce;
    private javax.swing.JMenuItem jmi_cj;
    private javax.swing.JMenuItem jmi_transfe;
    private javax.swing.JTextField tf_ciudad;
    private javax.swing.JTextField tf_estadio;
    private javax.swing.JTextField tf_nombreE;
    private javax.swing.JTextField tf_nombreJ;
    private javax.swing.JTextField tf_paisE;
    // End of variables declaration//GEN-END:variables
}
